### PR TITLE
Notifications API integration

### PR DESCRIPTION
**Pull request by JakeBooher**
Supports:
- Chrome 22+
- Firefox 22+
- Opera 25+
- Safari 6+ (OS X only and does not show icon)

### CODE REVIEW

**Comment by chrisdeeming** [comment]
Looks good.

I think this behaves a bit differently to how you suggested earlier, though. Am I right in saying this actually replaces the standard XF stack alert? Also wouldn't the OG logo be better than headerLogoPath?

**Comment by JakeBooher** [comment]
The stackAlert still runs just before the notification is created. That
image would definitely make more sense. I must've copied the wrong style
property. I'll fix that tomorrow and resend the PR

**Comment by JakeBooher** [comment]
@chrisdeeming Just pushed the update that changes the icon to the OG logo, also created an option to disable the notification integration completely :)

**Comment by chrisdeeming** [comment]
Thanks - I will merge this but I actually have some other changes I want to make so release won't be immediate.

**Comment by chrisdeeming** [comment]
@JakeBooher Download the latest version from master - I've made quite a few changes:
- Changed the favico library from tinycon to favico.js
- Changed the settings to be stored as a JSON array rather than a string value, allowing more flexibility
- Removed global option for Notification API as generally this add-on prefers user preferences
- Implemented a default registration value for Live Update settings
- Given the admin to deny users the ability to change the user preferences (new permission), in which case the default settings as specified in the aforementioned option will apply instead

I think that's everything. Give it a whirl. I'll post at XF.com and install at XenResources.com :+1:

**Pull request merged**
